### ISSUE TITLE
Better error messages for signup

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#12]
I know this is not a glamorous feature to add, but right now, when you try to make an account, if you give it invalid input, it gives you the same error message no matter why the input was invalid, so if your password is too short, it doesn't say, "password too short" it just says there's an error.

**Comment by judytuna** [comment]
Actually, it does show why the input was invalid. It gives really detailed error messages automatically, using the "validates" thingies in Rails, which is really cool. We just can't see it because our css makes the text white on a white background. hahahaha

**Comment by petersont** [comment]
All I have to do to fix it is change the color of stuff?  DONE.
