### ISSUE TITLE
Count down the number of characters left in the shortcode text field

### ISSUE THREAD

**Issue by judytuna** [judytuna/shortcode-site-309#16]
Add Javascript to the "new/edit entry" form (located at `app/views/entry/_fields.html.erb`) that counts down the available characters you have left as you type, like twitter does! Probably at the bottom right-hand corner of the text field.

Perhaps also display the number of characters used somewhere.

**Comment by petersont** [comment]
I did this, but the solution I found seems a little inelegant.  It uses an event timer, so it's checking whether the field is right every fifth or tenth of a second or something.  BUT ANYWAY, functionality implemented, closing issue.
