### ISSUE TITLE
Add Paperclip

### ISSUE THREAD

**Issue by judytuna** [judytuna/shortcode-site-309#2]
For each entry: after our magical rendering ec2 machine renders the given shortcode, use Paperclip to store the resulting image file.

**Comment by petersont** [comment]
I want to close this issue.  I don't know how to do get the picture from the ec2 machine to the website.  If that's really easy, let's do it, otherwise I'd like to either divide it into smaller issues, or give up.

**Comment by judytuna** [comment]
Yes. This issue was for when I thought the user would upload their
_own_ picture, but we don't want that anyway. Getting the picture from
the ec2 machine to the website (and storing it there?) is a whole
other issue entirely, you're right. Thanks =)

On Tue, Oct 18, 2011 at 2:06 PM, Peterson Trethewey
reply@reply.github.com
wrote:
