### ISSUE TITLE
Add a "render" button

### ISSUE THREAD

**Issue by judytuna** [judytuna/shortcode-site-309#3]
Allow a user to hit a button on their entry that says "render", which sends the shortcode text to our povray rendering cloud machine. IT'S THE FUTURE

**Comment by petersont** [comment]
I did this, but there's some stuff missing.  It doesn't render the thumbnails, and it doesn't copy the picture to the local database at all.  You can't render two things at once.  One user can easily render over another user's stuff.  Still I feel a sense of satisfaction.
