### ISSUE TITLE
Make function to get current contest.

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#35]
Everything needs to be able to see the current contest.  Something like Contest.get_current member of the class?  It'll live wherever it needs to to get everybody to be able to see it.

**Comment by judytuna** [comment]
We don't manually set a "current contest" variable anywhere. Instead, get_current (or whatever we name it) will look at the dates of all the contests and figure out which contest is going on. 

Should it also tell us what "phase" of the contest we're in? Discussed: no, keep it simple; we'll make something else that tells you the other things!!

**Comment by judytuna** [comment]
Done!!!
