### ISSUE TITLE
New entries get current contest id

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#39]
Let's assume that when the user makes a new entry, that it is supposed to be an entry into the current contest, and then set the contest_id to the right thing, and display that in the entry partial (not the id, but the title).

**Comment by judytuna** [comment]
Created a migration to add contest_id to the entries table in the database. Added a line in the entries controller, in the new method, that sets the contest_id to the current contest. Added a couple lines to the view to add some text to the "time ago" line. DONE WHOOOOSHHH
