### ISSUE TITLE
Make entries/index show thumbnails, not entire entries

### ISSUE THREAD

**Issue by judytuna** [judytuna/shortcode-site-309#4]
Well, entries/index (aka "all entries") should show title and picture thumbnail (with pagination). Clicking on either should bring you to the entry show page.

This probably calls for a thumbnail partial.

If logged in, there should also be some visual indicator of the entries you have already voted for. Perhaps they will have a different color box around them, and/or the entries you voted for will appear at the top of the first page. 

Decide: should there be a vote button for each entry on the "all entries" page?

**Comment by petersont** [comment]
I think I can do this.  I have to make the pov server render the thumbnail, so I can probably handle making those thumbnails show up wherever they need to.  I figure the entries belonging to just one user should also show the thumbnail, and really it's only when you view an entry all by itself that the full-sized images should show.  What do you think?

**Comment by petersont** [comment]
I did this, the thumbnail shows if the user has rendered the image.
