### ISSUE TITLE
Make time local timezone

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#43]
Not sure how to do this, but it's got to be possible.  The time in the timezone of the client machine.  That's got to be possible.

**Comment by judytuna** [comment]
https://github.com/judytuna/shortcode-site-309/commit/c9dd07fb991596008e990c47df8a1b90903c609f

used the instance method getlocal ... http://www.ruby-doc.org/core-1.9.2/Time.html
I haven't changed this everywhere, though. ONLY in the contest deadline listings in the header partial.
