### ISSUE TITLE
Fix the Entry partial

### ISSUE THREAD

**Issue by judytuna** [judytuna/shortcode-site-309#5]
It's totally broken right now.

Also need to add this functionality: 
-- when logged in as the user who created that entry, show an "edit" button.
-- when logged in as any other user, show the "vote/unvote" button.

**Comment by petersont** [comment]
I don't see what's wrong with the entry partial, it basically works except the pictures, doesn't it?

**Comment by judytuna** [comment]
It works on localhost, but is broken on heroku! The entire page won't render. I'll remove the paperclip picture lines and see if it works again.

**Comment by petersont** [comment]
Are you working on it right now?

On Mon, Oct 3, 2011 at 1:33 PM, Judy Tuan
reply@reply.github.com
wrote:

**Comment by judytuna** [comment]
Fixed (removed the paperclip picture lines). Putting the user privileges stuff in another issue. Closing this issue.
