### ISSUE TITLE
Add explanation to entry form

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#54]
It would be a good idea to add a brief explanation of what each field is in the entry form.  Particularly the longcode field.  Emphasize that it is optional whereas short code is the real entry that gets rendered and judged.

**Comment by judytuna** [comment]
Should we do the thing where there's an asterisk to denote a required 
field?

**Comment by petersont** [comment]
Totally.

On Mon, Nov 7, 2011 at 12:11 AM, Judy Tuan
reply@reply.github.com
wrote:
