### ISSUE TITLE
Only show full picture for a single entry.

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#9]
I think there needs to be a different view for single entries that shows the whole picture and everywhere else the picture appears it should be a thumb nail.

**Comment by petersont** [comment]
I don't know, maybe we don't want to do this.

**Comment by judytuna** [comment]
Maybe we want to do your mom!!!!!!!!!!!!

**Comment by petersont** [comment]
I'm closing this one.  It's fine the way it is.
